export type CuratedChallenge = {
  id: string;
  game: {
    title: string;
    steamAppId?: number;
  };
  title: string;
  description: string;
  difficulty: number;
  minPlayers: number;
  maxPlayers: number;
  platform: string;
  estimatedMinMinutes?: number;
  estimatedMaxMinutes?: number;
  caveat?: string;
  sourceName: string;
  sourceUrl: string;
  verifiedAt: string;
};

export const curatedChallenges: CuratedChallenge[] = [
  {
    id: "ready-or-not-all-missions-s-rank",
    game: { title: "Ready or Not", steamAppId: 1144200 },
    title: "S-rank every mission",
    description: "Complete the full mission set at S rank with disciplined non-lethal clears, evidence collection, and no officer losses.",
    difficulty: 5,
    minPlayers: 2,
    maxPlayers: 5,
    platform: "PC",
    estimatedMinMinutes: 2400,
    estimatedMaxMinutes: 6000,
    caveat: "Mission changes and major updates can alter the exact route and completion estimate.",
    sourceName: "Ready or Not official achievements",
    sourceUrl: "https://store.steampowered.com/stats/1144200/achievements",
    verifiedAt: "2026-07-01",
  },
  {
    id: "halo-mcc-laso",
    game: { title: "Halo: The Master Chief Collection", steamAppId: 976730 },
    title: "Complete a LASO playlist",
    description: "Finish a campaign on Legendary with the playlist's full skull set active.",
    difficulty: 5,
    minPlayers: 2,
    maxPlayers: 4,
    platform: "PC / Xbox",
    estimatedMinMinutes: 1200,
    estimatedMaxMinutes: 3600,
    caveat: "Supported co-op player counts differ between Halo campaigns.",
    sourceName: "Halo Support: campaign playlists",
    sourceUrl: "https://support.halowaypoint.com/hc/en-us/categories/360002381251-Halo-The-Master-Chief-Collection",
    verifiedAt: "2026-07-01",
  },
  {
    id: "deep-rock-elite-deep-dive",
    game: { title: "Deep Rock Galactic", steamAppId: 548430 },
    title: "Clear an Elite Deep Dive",
    description: "Complete all three consecutive Elite Deep Dive stages with one team and no mid-run loadout changes.",
    difficulty: 4,
    minPlayers: 2,
    maxPlayers: 4,
    platform: "PC / Xbox / PlayStation",
    estimatedMinMinutes: 90,
    estimatedMaxMinutes: 180,
    sourceName: "Deep Rock Galactic Wiki: Deep Dives",
    sourceUrl: "https://deeprockgalactic.wiki.gg/wiki/Deep_Dives",
    verifiedAt: "2026-07-01",
  },
  {
    id: "left-4-dead-2-realism-expert",
    game: { title: "Left 4 Dead 2", steamAppId: 550 },
    title: "Finish a campaign on Realism Expert",
    description: "Survive an entire campaign with Realism rules and Expert damage.",
    difficulty: 5,
    minPlayers: 2,
    maxPlayers: 4,
    platform: "PC / Xbox",
    estimatedMinMinutes: 120,
    estimatedMaxMinutes: 480,
    sourceName: "Valve Developer Community: Realism",
    sourceUrl: "https://developer.valvesoftware.com/wiki/Left_4_Dead_2/Realism",
    verifiedAt: "2026-07-01",
  },
  {
    id: "gtfo-rundown-finale",
    game: { title: "GTFO", steamAppId: 493520 },
    title: "Clear a Rundown finale",
    description: "Work through a Rundown and complete its deepest available expedition as a coordinated squad.",
    difficulty: 5,
    minPlayers: 3,
    maxPlayers: 4,
    platform: "PC",
    estimatedMinMinutes: 1800,
    estimatedMaxMinutes: 6000,
    caveat: "Rundown structure and expedition availability change with game updates.",
    sourceName: "GTFO official Rundown overview",
    sourceUrl: "https://gtfothegame.com/",
    verifiedAt: "2026-07-01",
  },
  {
    id: "helldivers-2-super-helldive-operation",
    game: { title: "HELLDIVERS 2", steamAppId: 553850 },
    title: "Complete a full Super Helldive operation",
    description: "Finish every mission in a difficulty-10 operation without abandoning the campaign.",
    difficulty: 4,
    minPlayers: 2,
    maxPlayers: 4,
    platform: "PC / PlayStation / Xbox",
    estimatedMinMinutes: 90,
    estimatedMaxMinutes: 180,
    sourceName: "HELLDIVERS 2 official game page",
    sourceUrl: "https://www.playstation.com/games/helldivers-2/",
    verifiedAt: "2026-07-01",
  },
  {
    id: "destiny-2-flawless-raid",
    game: { title: "Destiny 2", steamAppId: 1085660 },
    title: "Complete a flawless raid",
    description: "Clear a full raid with no fireteam deaths from launch to final encounter.",
    difficulty: 5,
    minPlayers: 6,
    maxPlayers: 6,
    platform: "PC / PlayStation / Xbox",
    estimatedMinMinutes: 180,
    estimatedMaxMinutes: 1200,
    caveat: "Raid availability, power requirements, and triumph conditions vary by season.",
    sourceName: "Bungie Destiny 2 raids",
    sourceUrl: "https://www.bungie.net/7/en/Destiny",
    verifiedAt: "2026-07-01",
  },
  {
    id: "monster-hunter-world-fatalis",
    game: { title: "Monster Hunter: World", steamAppId: 582010 },
    title: "Defeat Fatalis as a group",
    description: "Prepare a coordinated hunting party and clear the Fatalis special assignment within its time limit.",
    difficulty: 5,
    minPlayers: 2,
    maxPlayers: 4,
    platform: "PC / PlayStation / Xbox",
    estimatedMinMinutes: 600,
    estimatedMaxMinutes: 2400,
    caveat: "Estimate includes gearing and repeated attempts, not the full preceding campaign requirement.",
    sourceName: "Monster Hunter World official update notes",
    sourceUrl: "https://www.monsterhunter.com/update/mhw/us/",
    verifiedAt: "2026-07-01",
  },
  {
    id: "payday-2-one-down",
    game: { title: "PAYDAY 2", steamAppId: 218620 },
    title: "Complete a heist on Death Sentence One Down",
    description: "Clear a full heist at the highest standard difficulty with the One Down modifier enabled.",
    difficulty: 5,
    minPlayers: 2,
    maxPlayers: 4,
    platform: "PC",
    estimatedMinMinutes: 60,
    estimatedMaxMinutes: 480,
    sourceName: "PAYDAY 2 official game page",
    sourceUrl: "https://www.paydaythegame.com/payday2/",
    verifiedAt: "2026-07-01",
  },
  {
    id: "portal-2-coop-no-deaths",
    game: { title: "Portal 2", steamAppId: 620 },
    title: "Complete co-op with no chamber deaths",
    description: "Run the cooperative campaign together and aim for a clean, reset-free solution to every chamber.",
    difficulty: 3,
    minPlayers: 2,
    maxPlayers: 2,
    platform: "PC / Console",
    estimatedMinMinutes: 360,
    estimatedMaxMinutes: 900,
    caveat: "This is an editorial challenge built from the official two-player cooperative campaign.",
    sourceName: "Portal 2 official store page",
    sourceUrl: "https://store.steampowered.com/app/620/Portal_2/",
    verifiedAt: "2026-07-01",
  },
];
