import { type GameInput } from "@/lib/games";

export type LocalSetup = "phones" | "controllers" | "shared-controller" | "pass-and-play" | "single-device";

export type CuratedGame = GameInput & {
  slug: string;
  description: string;
  listSlugs: string[];
  tags: string[];
  sessionLength: "one-night" | "long-term" | "campaign";
  trending?: boolean;
  releaseStatus?: "released" | "recent" | "upcoming";
  caveat?: string;
  localSetup?: LocalSetup;
  localRequirement?: string;
  moddedPlayersLabel?: string;
  moddedMaxPlayers?: number;
  moddedSupportNote?: string;
  moddedUnrestricted?: boolean;
  moddedSourceName?: string;
  moddedSourceUrl?: string;
};

export type CuratedList = {
  slug: string;
  title: string;
  description: string;
};

type CuratedGameSeed = {
  slug: string;
  title: string;
  description: string;
  listSlugs: string[];
  tags: string[];
  sessionLength: CuratedGame["sessionLength"];
  steamAppId?: number;
  minPlayers: number;
  maxPlayers: number;
  onlineCoop: boolean;
  localCoop: boolean;
  platforms?: string[];
  trending?: boolean;
  releaseStatus?: CuratedGame["releaseStatus"];
  caveat?: string;
  localSetup?: LocalSetup;
  localRequirement?: string;
  moddedPlayersLabel?: string;
  moddedMaxPlayers?: number;
  moddedSupportNote?: string;
  moddedUnrestricted?: boolean;
  moddedSourceName?: string;
  moddedSourceUrl?: string;
};

export const curatedLists: CuratedList[] = [
  { slug: "online-co-op", title: "Best online co-op games", description: "Games that make it easy for a remote group to jump in together." },
  { slug: "local-co-op", title: "Best local co-op games", description: "Couch-friendly games for one screen or one room." },
  { slug: "4-player", title: "Best 4-player games", description: "Reliable picks for the classic four-player group." },
  { slug: "more-than-4", title: "More than 4?", description: "Bigger lobbies, party chaos, survival servers, and social deduction nights. Use the player slider to separate 5+, 10+, 16+, or 50+ needs." },
  { slug: "party", title: "Best party games", description: "Low-friction picks for mixed groups and casual nights." },
  { slug: "campaign-co-op", title: "Best campaign co-op games", description: "Longer shared adventures with meaningful progression." },
  { slug: "survival-groups", title: "Best survival games for groups", description: "Build, explore, panic, regroup, repeat." },
  { slug: "cheap-co-op", title: "Best cheap co-op games", description: "Budget-friendly group picks, especially when deals are live." },
  { slug: "trending-multiplayer", title: "Trending multiplayer games", description: "Currently hot multiplayer picks worth checking." },
  { slug: "recently-released", title: "Recently released group games", description: "Fresh multiplayer releases and current viral picks." },
  { slug: "friend-slop", title: "Fresh and upcoming friend-slop", description: "Messy, funny, highly shareable games for group discovery." },
  { slug: "with-mods", title: "With mods", description: "Games that are solo or limited by default, but become strong group picks through community mods or server setups." },
];

export const curatedGames: CuratedGame[] = [
  game({ slug: "meccha-chameleon", title: "Meccha Chameleon", description: "A viral paint-and-hide party game with chaotic lobbies and strong spectator energy.", listSlugs: ["recently-released", "friend-slop", "party", "more-than-4", "more-than-4", "cheap-co-op", "trending-multiplayer"], tags: ["hide and seek", "party", "viral"], sessionLength: "one-night", steamAppId: 4704690, minPlayers: 2, maxPlayers: 24, onlineCoop: true, localCoop: false, platforms: ["PC", "Steam"], trending: true, releaseStatus: "recent", caveat: "Recommended around 2-10 players; larger rooms depend heavily on host connection and stability." }),
  game({ slug: "big-walk", title: "Big Walk", description: "A cooperative walker-talker from House House built around getting lost and communicating with friends.", listSlugs: ["friend-slop", "online-co-op", "more-than-4", "party"], tags: ["co-op", "communication", "adventure"], sessionLength: "one-night", steamAppId: 1478500, minPlayers: 2, maxPlayers: 12, onlineCoop: true, localCoop: false, platforms: ["PC", "Mac", "PlayStation 5", "Switch 2"], trending: true, releaseStatus: "upcoming", caveat: "Planned for August 4, 2026; use as a wishlist/upcoming pick until release." }),
  game({ slug: "repo", title: "R.E.P.O.", description: "Scrappy physics horror extraction for groups who enjoy panic, betrayal, and bad decisions.", listSlugs: ["friend-slop", "online-co-op", "more-than-4", "party", "trending-multiplayer", "with-mods"], tags: ["horror", "physics", "friendslop"], sessionLength: "one-night", steamAppId: 3241660, minPlayers: 1, maxPlayers: 6, onlineCoop: true, localCoop: false, trending: true, releaseStatus: "recent", caveat: "Native lobbies are capped at 6. Larger rooms depend on community mods and can be less stable.", moddedPlayersLabel: "6+ with mods", moddedMaxPlayers: 16, moddedSupportNote: "Community lobby-size mods can push past the native cap; treat this as best-effort rather than guaranteed support.", moddedUnrestricted: true, moddedSourceName: "community lobby-size mods" }),
  game({ slug: "peak", title: "PEAK", description: "Climb, fall, shout, recover: a compact co-op chaos pick for a small group.", listSlugs: ["friend-slop", "online-co-op", "party", "recently-released"], tags: ["co-op", "climbing", "chaos"], sessionLength: "one-night", steamAppId: 3527290, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false, trending: true, releaseStatus: "recent" }),
  game({ slug: "content-warning", title: "Content Warning", description: "Film spooky nonsense with friends and try to survive long enough to upload it.", listSlugs: ["friend-slop", "online-co-op", "4-player", "party"], tags: ["horror", "co-op", "comedy"], sessionLength: "one-night", steamAppId: 2881650, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false, trending: true }),
  game({ slug: "lethal-company", title: "Lethal Company", description: "Scrappy co-op horror built for laughs, panic, and clips.", listSlugs: ["online-co-op", "4-player", "party", "friend-slop", "cheap-co-op"], tags: ["horror", "co-op", "party"], sessionLength: "one-night", steamAppId: 1966720, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false, trending: true }),
  game({ slug: "phasmophobia", title: "Phasmophobia", description: "Co-op ghost hunting with strong one-night energy.", listSlugs: ["online-co-op", "4-player", "party"], tags: ["horror", "co-op"], sessionLength: "one-night", steamAppId: 739630, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false }),

  game({ slug: "deep-rock-galactic", title: "Deep Rock Galactic", description: "Co-op mining chaos with strong 4-player teamwork.", listSlugs: ["online-co-op", "4-player", "cheap-co-op"], tags: ["co-op", "shooter", "dwarves"], sessionLength: "long-term", steamAppId: 548430, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false }),
  game({ slug: "helldivers-2", title: "HELLDIVERS 2", description: "Explosive online co-op with fast missions and big group energy.", listSlugs: ["online-co-op", "4-player", "trending-multiplayer"], tags: ["co-op", "shooter", "intense"], sessionLength: "long-term", steamAppId: 553850, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false, trending: true }),
  game({ slug: "sea-of-thieves", title: "Sea of Thieves", description: "Pirate co-op with sessions that naturally turn into stories.", listSlugs: ["online-co-op", "4-player", "campaign-co-op"], tags: ["co-op", "adventure", "open world"], sessionLength: "long-term", steamAppId: 1172620, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false }),
  game({ slug: "monster-hunter-wilds", title: "Monster Hunter Wilds", description: "Big hunts, repeated sessions, and a natural fit for a committed four-player group.", listSlugs: ["online-co-op", "4-player", "campaign-co-op", "trending-multiplayer"], tags: ["action", "co-op", "campaign"], sessionLength: "long-term", steamAppId: 2246340, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false, trending: true }),
  game({ slug: "warhammer-vermintide-2", title: "Warhammer: Vermintide 2", description: "Melee-focused horde co-op with a mountain of classes and progression.", listSlugs: ["online-co-op", "4-player", "cheap-co-op"], tags: ["co-op", "horde", "melee"], sessionLength: "long-term", steamAppId: 552500, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false }),
  game({ slug: "left-4-dead-2", title: "Left 4 Dead 2", description: "Still one of the cleanest templates for a co-op campaign night.", listSlugs: ["online-co-op", "4-player", "campaign-co-op", "cheap-co-op"], tags: ["co-op", "campaign", "zombies"], sessionLength: "one-night", steamAppId: 550, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true }),
  game({ slug: "risk-of-rain-2", title: "Risk of Rain 2", description: "Stack absurd builds together and turn a short run into a disaster story.", listSlugs: ["online-co-op", "4-player"], tags: ["roguelite", "co-op", "action"], sessionLength: "one-night", steamAppId: 632360, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false }),
  game({ slug: "baldurs-gate-3", title: "Baldur's Gate 3", description: "A deep campaign co-op choice for committed groups.", listSlugs: ["online-co-op", "campaign-co-op", "4-player"], tags: ["rpg", "campaign", "turn-based"], sessionLength: "campaign", steamAppId: 1086940, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true }),

  game({ slug: "overcooked-2", title: "Overcooked! 2", description: "Local and online co-op stress disguised as cooking.", listSlugs: ["local-co-op", "online-co-op", "4-player", "party"], tags: ["co-op", "party", "chaos"], sessionLength: "one-night", steamAppId: 728880, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "plateup", title: "PlateUp!", description: "Restaurant roguelite co-op with satisfying group escalation.", listSlugs: ["local-co-op", "online-co-op", "4-player", "party"], tags: ["co-op", "roguelite", "management"], sessionLength: "one-night", steamAppId: 1599600, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "ultimate-chicken-horse", title: "Ultimate Chicken Horse", description: "Build the level, sabotage the level, pretend it was fair.", listSlugs: ["local-co-op", "online-co-op", "4-player", "party", "cheap-co-op"], tags: ["party", "platformer", "competitive"], sessionLength: "one-night", steamAppId: 386940, minPlayers: 2, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "towerfall-ascension", title: "TowerFall Ascension", description: "Tiny arena archery with instant readability and local chaos.", listSlugs: ["local-co-op", "4-player", "party", "cheap-co-op"], tags: ["local", "party", "arena"], sessionLength: "one-night", steamAppId: 251470, minPlayers: 2, maxPlayers: 4, onlineCoop: false, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "pico-park", title: "PICO PARK", description: "Simple cooperative puzzles that get funnier as communication breaks down.", listSlugs: ["local-co-op", "online-co-op", "more-than-4", "party", "cheap-co-op"], tags: ["puzzle", "party", "co-op"], sessionLength: "one-night", steamAppId: 1509960, minPlayers: 2, maxPlayers: 8, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 8, share controllers/keyboard" }),
  game({ slug: "stardew-valley", title: "Stardew Valley", description: "Chill farming co-op that works for short visits or long campaigns.", listSlugs: ["online-co-op", "local-co-op", "campaign-co-op", "cheap-co-op", "more-than-4"], tags: ["chill", "farming", "campaign"], sessionLength: "campaign", steamAppId: 413150, minPlayers: 1, maxPlayers: 8, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 split-screen (controllers)" }),

  // Local co-op — phones as controllers
  game({ slug: "jackbox-party-pack-9", title: "The Jackbox Party Pack 9", description: "Five more phone-controlled party games for a full room or a Discord call.", listSlugs: ["local-co-op", "party", "more-than-4"], tags: ["party", "quiz", "casual"], sessionLength: "one-night", steamAppId: 1850960, minPlayers: 1, maxPlayers: 10, onlineCoop: false, localCoop: true, localSetup: "phones", localRequirement: "Phones as controllers — no pads" }),
  game({ slug: "drawful-2", title: "Drawful 2", description: "Draw terrible prompts on your phone and bluff everyone else into guessing them.", listSlugs: ["local-co-op", "party", "cheap-co-op"], tags: ["party", "drawing", "casual"], sessionLength: "one-night", steamAppId: 442070, minPlayers: 3, maxPlayers: 8, onlineCoop: false, localCoop: true, localSetup: "phones", localRequirement: "Phones as controllers — no pads" }),
  game({ slug: "quiplash", title: "Quiplash", description: "Head-to-head answer battles judged by the whole room, all played from phones.", listSlugs: ["local-co-op", "party", "cheap-co-op"], tags: ["party", "comedy", "casual"], sessionLength: "one-night", steamAppId: 351510, minPlayers: 3, maxPlayers: 8, onlineCoop: false, localCoop: true, localSetup: "phones", localRequirement: "Phones as controllers — no pads" }),
  game({ slug: "use-your-words", title: "Use Your Words", description: "A party game for funny people and the friends who can't draw, played on phones.", listSlugs: ["local-co-op", "party", "cheap-co-op"], tags: ["party", "comedy", "casual"], sessionLength: "one-night", steamAppId: 521350, minPlayers: 3, maxPlayers: 6, onlineCoop: false, localCoop: true, localSetup: "phones", localRequirement: "Phones as controllers — no pads" }),

  // Local co-op — couch controllers
  game({ slug: "duck-game", title: "Duck Game", description: "Lightning-fast 8-duck couch deathmatch where one shot ends a round.", listSlugs: ["local-co-op", "party", "cheap-co-op", "more-than-4"], tags: ["party", "arena", "chaos"], sessionLength: "one-night", steamAppId: 312530, minPlayers: 2, maxPlayers: 8, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 8 controllers" }),
  game({ slug: "stick-fight-the-game", title: "Stick Fight: The Game", description: "Physics-driven stickman brawling that's pure couch chaos.", listSlugs: ["local-co-op", "party", "cheap-co-op", "4-player"], tags: ["party", "fighting", "physics"], sessionLength: "one-night", steamAppId: 674940, minPlayers: 2, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "move-or-die", title: "Move or Die", description: "Friendship-ruining minigames where standing still means death.", listSlugs: ["local-co-op", "party", "cheap-co-op", "4-player"], tags: ["party", "minigames", "competitive"], sessionLength: "one-night", steamAppId: 323850, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "speedrunners", title: "SpeedRunners", description: "Side-scrolling race-and-sabotage where last place gets eliminated.", listSlugs: ["local-co-op", "party", "cheap-co-op", "4-player"], tags: ["party", "racing", "competitive"], sessionLength: "one-night", steamAppId: 207140, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "samurai-gunn-2", title: "Samurai Gunn 2", description: "Frame-perfect sword-and-gun duels with instant, readable couch chaos.", listSlugs: ["local-co-op", "party", "4-player"], tags: ["arena", "fighting", "local"], sessionLength: "one-night", steamAppId: 1397790, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "castle-crashers", title: "Castle Crashers", description: "A beat-'em-up co-op classic that still anchors a couch night.", listSlugs: ["local-co-op", "online-co-op", "cheap-co-op", "4-player"], tags: ["beat-em-up", "co-op", "rpg"], sessionLength: "one-night", steamAppId: 204360, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "broforce", title: "Broforce", description: "Explosive run-and-gun co-op where the whole level is destructible.", listSlugs: ["local-co-op", "online-co-op", "cheap-co-op", "4-player"], tags: ["co-op", "platformer", "chaos"], sessionLength: "one-night", steamAppId: 274190, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "magicka-2", title: "Magicka 2", description: "Friendly-fire spell-combining co-op that punishes panic and bad aim.", listSlugs: ["local-co-op", "online-co-op", "cheap-co-op", "4-player"], tags: ["co-op", "magic", "chaos"], sessionLength: "one-night", steamAppId: 238370, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "crawl", title: "Crawl", description: "One player is the hero; everyone else possesses monsters to kill them.", listSlugs: ["local-co-op", "party", "cheap-co-op", "4-player"], tags: ["dungeon", "competitive", "local"], sessionLength: "one-night", steamAppId: 293780, minPlayers: 1, maxPlayers: 4, onlineCoop: false, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "brawlhalla", title: "Brawlhalla", description: "Free platform-fighter with deep local versus for a controller pile-up.", listSlugs: ["local-co-op", "party", "cheap-co-op", "more-than-4"], tags: ["platform fighter", "party", "competitive"], sessionLength: "one-night", steamAppId: 291550, minPlayers: 1, maxPlayers: 8, onlineCoop: false, localCoop: true, localSetup: "controllers", localRequirement: "Up to 8 controllers", caveat: "Free-to-play. 8 local is supported, though default PC controller drivers often work most reliably around 4." }),
  game({ slug: "heave-ho", title: "Heave Ho", description: "Cling, swing, and fling each other across gaps in panicked co-op.", listSlugs: ["local-co-op", "party", "cheap-co-op", "4-player"], tags: ["co-op", "physics", "chaos"], sessionLength: "one-night", steamAppId: 905340, minPlayers: 1, maxPlayers: 4, onlineCoop: false, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "hidden-in-plain-sight", title: "Hidden in Plain Sight", description: "Blend into a crowd of NPCs and assassinate friends without being spotted.", listSlugs: ["local-co-op", "party", "cheap-co-op", "4-player"], tags: ["party", "stealth", "local"], sessionLength: "one-night", steamAppId: 303590, minPlayers: 2, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers" }),
  game({ slug: "bombsquad", title: "BombSquad", description: "Free explosive mini-game brawler that scales to a full living room of players.", listSlugs: ["local-co-op", "party", "more-than-4"], tags: ["party", "explosions", "chaos"], sessionLength: "one-night", minPlayers: 1, maxPlayers: 8, onlineCoop: true, localCoop: true, platforms: ["PC", "Mac", "Android", "Mobile"], localSetup: "controllers", localRequirement: "Up to 8 controllers (or phones)", caveat: "Free. Not on Steam — download from the official BombSquad site; phones can also join as gamepads." }),

  // Local co-op — collaboration / one shared screen
  game({ slug: "keep-talking-and-nobody-explodes", title: "Keep Talking and Nobody Explodes", description: "One person defuses the bomb while everyone else frantically reads the manual.", listSlugs: ["local-co-op", "party", "cheap-co-op"], tags: ["co-op", "communication", "puzzle"], sessionLength: "one-night", steamAppId: 341800, minPlayers: 2, maxPlayers: 6, onlineCoop: false, localCoop: true, localSetup: "single-device", localRequirement: "1 device — everyone reads the manual", caveat: "Only one copy needed: one player drives, the rest read the free printable/PDF Bomb Defusal Manual. Scales to a whole room." }),
  game({ slug: "lovers-in-a-dangerous-spacetime", title: "Lovers in a Dangerous Spacetime", description: "Run one neon spaceship together, sprinting between turrets, shields, and the wheel.", listSlugs: ["local-co-op", "online-co-op", "cheap-co-op", "4-player"], tags: ["co-op", "space", "frantic"], sessionLength: "one-night", steamAppId: 252110, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "1 ship, up to 4 controllers" }),
  game({ slug: "death-squared", title: "Death Squared", description: "Guide cubes to their goals without triggering each other's lethal traps.", listSlugs: ["local-co-op", "cheap-co-op", "4-player"], tags: ["co-op", "puzzle", "communication"], sessionLength: "one-night", steamAppId: 471810, minPlayers: 1, maxPlayers: 4, onlineCoop: false, localCoop: true, localSetup: "controllers", localRequirement: "Up to 4 controllers (2 for story)" }),
  game({ slug: "it-takes-two", title: "It Takes Two", description: "A two-player-only co-op adventure that constantly reinvents how you cooperate.", listSlugs: ["local-co-op", "online-co-op", "campaign-co-op"], tags: ["co-op", "adventure", "campaign"], sessionLength: "campaign", steamAppId: 1426210, minPlayers: 2, maxPlayers: 2, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "2 controllers (split-screen)", caveat: "Co-op only — no solo mode. One Friend's Pass copy can cover the second player online." }),

  // Local co-op — shared / pass-and-play
  game({ slug: "brothers-a-tale-of-two-sons", title: "Brothers: A Tale of Two Sons", description: "Control both brothers at once — or hand a stick each to two people on one pad.", listSlugs: ["local-co-op", "cheap-co-op"], tags: ["adventure", "story", "shared"], sessionLength: "one-night", steamAppId: 225080, minPlayers: 1, maxPlayers: 2, onlineCoop: false, localCoop: true, localSetup: "shared-controller", localRequirement: "1 controller — 2 can share (a stick each)", caveat: "Designed as single-player (one person, both sticks); two people sharing one pad is a popular unofficial way to play." }),
  game({ slug: "worms-wmd", title: "Worms W.M.D", description: "Turn-based artillery warfare made for passing one controller around the couch.", listSlugs: ["local-co-op", "party", "cheap-co-op", "more-than-4"], tags: ["turn-based", "artillery", "hotseat"], sessionLength: "one-night", steamAppId: 327030, minPlayers: 1, maxPlayers: 6, onlineCoop: true, localCoop: true, localSetup: "pass-and-play", localRequirement: "Hotseat — pass one controller (up to 6)" }),
  game({ slug: "nidhogg-2", title: "Nidhogg 2", description: "Tug-of-war fencing duels with a built-in pass-the-controller tournament mode.", listSlugs: ["local-co-op", "party", "cheap-co-op"], tags: ["fencing", "competitive", "local"], sessionLength: "one-night", steamAppId: 535520, minPlayers: 1, maxPlayers: 8, onlineCoop: true, localCoop: true, localSetup: "pass-and-play", localRequirement: "2 at a time — up to 8 by swapping in" }),

  game({ slug: "valheim", title: "Valheim", description: "Survival crafting with broad group goals and low pressure pacing.", listSlugs: ["online-co-op", "survival-groups", "cheap-co-op", "more-than-4"], tags: ["survival", "crafting", "open world"], sessionLength: "long-term", steamAppId: 892970, minPlayers: 1, maxPlayers: 10, onlineCoop: true, localCoop: false, caveat: "Best for larger groups with a persistent hosted world." }),
  game({ slug: "project-zomboid", title: "Project Zomboid", description: "Deep survival sandbox for patient group storytelling.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4"], tags: ["survival", "sandbox", "hardcore"], sessionLength: "long-term", steamAppId: 108600, minPlayers: 1, maxPlayers: 32, onlineCoop: true, localCoop: false, caveat: "Large groups are best on a dedicated server with agreed rules." }),
  game({ slug: "minecraft", title: "Minecraft", description: "The default large-group sandbox: build, survive, mod, or host a private event.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4", "party"], tags: ["sandbox", "survival", "server"], sessionLength: "long-term", minPlayers: 1, maxPlayers: 30, onlineCoop: true, localCoop: true, platforms: ["PC", "Xbox", "PlayStation", "Switch", "Mobile"], caveat: "16+ works best with a Realm or dedicated/community server." }),
  game({ slug: "terraria", title: "Terraria", description: "Bosses, building, exploration, and long-term chaos for a medium group.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "cheap-co-op"], tags: ["sandbox", "crafting", "bosses"], sessionLength: "long-term", steamAppId: 105600, minPlayers: 1, maxPlayers: 8, onlineCoop: true, localCoop: false }),
  game({ slug: "core-keeper", title: "Core Keeper", description: "Underground survival crafting that scales nicely beyond a small squad.", listSlugs: ["online-co-op", "survival-groups", "more-than-4"], tags: ["survival", "crafting", "co-op"], sessionLength: "long-term", steamAppId: 1621690, minPlayers: 1, maxPlayers: 8, onlineCoop: true, localCoop: false }),
  game({ slug: "enshrouded", title: "Enshrouded", description: "Voxel survival RPG with a meaningful 16-player ceiling for hosted worlds.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4"], tags: ["survival", "rpg", "server"], sessionLength: "long-term", steamAppId: 1203620, minPlayers: 1, maxPlayers: 16, onlineCoop: true, localCoop: false, caveat: "Use a hosted or dedicated server for smooth 16-player sessions." }),
  game({ slug: "palworld", title: "Palworld", description: "Creature survival chaos that can scale up when hosted properly.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4", "trending-multiplayer"], tags: ["survival", "crafting", "server"], sessionLength: "long-term", steamAppId: 1623730, minPlayers: 1, maxPlayers: 32, onlineCoop: true, localCoop: false, caveat: "Large groups require a dedicated server; small co-op is simpler." }),
  game({ slug: "ark-survival-ascended", title: "ARK: Survival Ascended", description: "Dinosaur survival for groups who want a persistent server project.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4"], tags: ["survival", "dinosaurs", "server"], sessionLength: "long-term", steamAppId: 2399830, minPlayers: 1, maxPlayers: 70, onlineCoop: true, localCoop: false, caveat: "16+ is a server-hosting commitment, not a casual lobby." }),
  game({ slug: "factorio", title: "Factorio", description: "A shared factory project that gets funnier and more terrifying with each extra engineer.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4"], tags: ["automation", "factory", "server"], sessionLength: "long-term", steamAppId: 427520, minPlayers: 1, maxPlayers: 32, onlineCoop: true, localCoop: false, caveat: "Large groups work best with a persistent server and clear roles." }),
  game({ slug: "satisfactory", title: "Satisfactory", description: "First-person factory building for a group that enjoys shared megaprojects.", listSlugs: ["online-co-op", "survival-groups", "more-than-4"], tags: ["factory", "building", "co-op"], sessionLength: "long-term", steamAppId: 526870, minPlayers: 1, maxPlayers: 8, onlineCoop: true, localCoop: false, caveat: "Bigger groups are possible through server setups, but 4-8 is the clean recommendation." }),
  game({ slug: "eco", title: "Eco", description: "A civilization-scale server game about building society without destroying the planet.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4"], tags: ["server", "simulation", "society"], sessionLength: "long-term", steamAppId: 382310, minPlayers: 1, maxPlayers: 30, onlineCoop: true, localCoop: false, caveat: "Needs a persistent server and a group willing to coordinate over days." }),
  game({ slug: "barotrauma", title: "Barotrauma", description: "Submarine disaster management for groups who enjoy jobs, shouting, and betrayal.", listSlugs: ["online-co-op", "more-than-4", "more-than-4", "party"], tags: ["submarine", "roles", "chaos"], sessionLength: "one-night", steamAppId: 602960, minPlayers: 2, maxPlayers: 16, onlineCoop: true, localCoop: false }),
  game({ slug: "unturned", title: "Unturned", description: "Lightweight zombie survival with private-server flexibility.", listSlugs: ["online-co-op", "survival-groups", "more-than-4", "more-than-4", "cheap-co-op"], tags: ["survival", "zombies", "server"], sessionLength: "long-term", steamAppId: 304930, minPlayers: 1, maxPlayers: 24, onlineCoop: true, localCoop: false, caveat: "Best for 16+ with a private server and agreed mods/settings." }),
  game({ slug: "rust", title: "Rust", description: "Brutal social survival for groups who specifically want a server war story.", listSlugs: ["survival-groups", "more-than-4", "more-than-4"], tags: ["survival", "pvp", "server"], sessionLength: "long-term", steamAppId: 252490, minPlayers: 1, maxPlayers: 100, onlineCoop: true, localCoop: false, caveat: "Not cosy co-op. Works for 16+ only if the group wants PvP survival friction." }),

  game({ slug: "among-us", title: "Among Us", description: "Social deduction that scales well beyond the usual four.", listSlugs: ["party", "more-than-4", "cheap-co-op"], tags: ["social deduction", "party"], sessionLength: "one-night", steamAppId: 945360, minPlayers: 4, maxPlayers: 15, onlineCoop: true, localCoop: true }),
  game({ slug: "goose-goose-duck", title: "Goose Goose Duck", description: "Social deduction with lots of roles and room for a large voice call.", listSlugs: ["party", "more-than-4", "more-than-4", "cheap-co-op"], tags: ["social deduction", "party", "roles"], sessionLength: "one-night", steamAppId: 1568590, minPlayers: 5, maxPlayers: 16, onlineCoop: true, localCoop: false }),
  game({ slug: "jackbox-party-pack-10", title: "The Jackbox Party Pack 10", description: "Phone-controlled party games for mixed groups.", listSlugs: ["party", "more-than-4", "local-co-op"], tags: ["party", "quiz", "casual"], sessionLength: "one-night", steamAppId: 2216830, minPlayers: 1, maxPlayers: 10, onlineCoop: false, localCoop: true, localSetup: "phones", localRequirement: "Phones as controllers — no pads" }),
  game({ slug: "gartic-phone", title: "Gartic Phone", description: "Browser-based drawing telephone that works for huge casual groups.", listSlugs: ["party", "more-than-4", "more-than-4"], tags: ["drawing", "browser", "party"], sessionLength: "one-night", minPlayers: 4, maxPlayers: 30, onlineCoop: true, localCoop: false, platforms: ["Browser"], caveat: "Browser game; not a Steam import match, but excellent for big groups." }),
  game({ slug: "skribbl-io", title: "skribbl.io", description: "Fast browser drawing rounds for groups that need zero install friction.", listSlugs: ["party", "more-than-4", "more-than-4"], tags: ["drawing", "browser", "party"], sessionLength: "one-night", minPlayers: 3, maxPlayers: 20, onlineCoop: true, localCoop: false, platforms: ["Browser"], caveat: "Browser game; great backup when ownership is fragmented." }),
  game({ slug: "golf-with-your-friends", title: "Golf With Your Friends", description: "Readable, casual minigolf that can carry a full Discord call.", listSlugs: ["party", "more-than-4", "cheap-co-op"], tags: ["party", "golf", "casual"], sessionLength: "one-night", steamAppId: 431240, minPlayers: 1, maxPlayers: 12, onlineCoop: true, localCoop: true }),
  game({ slug: "gang-beasts", title: "Gang Beasts", description: "Local or online physics brawling that gets sillier as people rotate in.", listSlugs: ["party", "local-co-op", "online-co-op", "more-than-4"], tags: ["party", "fighting", "physics"], sessionLength: "one-night", steamAppId: 285900, minPlayers: 2, maxPlayers: 8, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 8 controllers" }),
  game({ slug: "party-animals", title: "Party Animals", description: "Physics brawling made for casual group nights.", listSlugs: ["party", "local-co-op", "online-co-op", "more-than-4"], tags: ["party", "fighting", "casual"], sessionLength: "one-night", steamAppId: 1260320, minPlayers: 2, maxPlayers: 8, onlineCoop: true, localCoop: true, localSetup: "controllers", localRequirement: "Up to 8 controllers" }),
  game({ slug: "crab-game", title: "Crab Game", description: "Chaotic elimination rounds for very large, unserious groups.", listSlugs: ["party", "more-than-4", "more-than-4", "cheap-co-op"], tags: ["party", "elimination", "chaos"], sessionLength: "one-night", steamAppId: 1782210, minPlayers: 2, maxPlayers: 40, onlineCoop: true, localCoop: false }),
  game({ slug: "garrys-mod", title: "Garry's Mod", description: "Prop Hunt, Trouble in Terrorist Town, sandbox chaos: still a big-group toolbox.", listSlugs: ["party", "more-than-4", "more-than-4", "friend-slop"], tags: ["sandbox", "mods", "party"], sessionLength: "one-night", steamAppId: 4000, minPlayers: 2, maxPlayers: 32, onlineCoop: true, localCoop: false, caveat: "Requires choosing a mode/server; great once someone hosts." }),

  game({ slug: "counter-strike-2", title: "Counter-Strike 2", description: "Private lobbies and custom servers for groups that want teams, aim, or chaos modes.", listSlugs: ["more-than-4", "more-than-4", "party"], tags: ["shooter", "pvp", "server"], sessionLength: "one-night", steamAppId: 730, minPlayers: 2, maxPlayers: 20, onlineCoop: true, localCoop: false, caveat: "Best for 10+ as private teams or community/custom server modes." }),
  game({ slug: "team-fortress-2", title: "Team Fortress 2", description: "Large-team class shooter with a massive history of silly server nights.", listSlugs: ["more-than-4", "more-than-4", "cheap-co-op", "party"], tags: ["shooter", "classes", "server"], sessionLength: "one-night", steamAppId: 440, minPlayers: 2, maxPlayers: 24, onlineCoop: true, localCoop: false }),
  game({ slug: "battlebit-remastered", title: "BattleBit Remastered", description: "Huge low-poly battlefield chaos if your group wants to pile into the same war.", listSlugs: ["more-than-4", "more-than-4"], tags: ["shooter", "large scale", "pvp"], sessionLength: "one-night", steamAppId: 671860, minPlayers: 2, maxPlayers: 254, onlineCoop: true, localCoop: false, caveat: "Not private-party focused, but excellent for large groups joining together." }),
  game({ slug: "foxhole", title: "Foxhole", description: "Persistent war logistics for groups that want a shared long-term campaign.", listSlugs: ["more-than-4", "more-than-4", "campaign-co-op"], tags: ["war", "logistics", "persistent"], sessionLength: "campaign", steamAppId: 505460, minPlayers: 1, maxPlayers: 50, onlineCoop: true, localCoop: false, caveat: "Best when the group joins the same faction and treats it as an ongoing campaign." }),
  game({ slug: "vrchat", title: "VRChat", description: "Social worlds, party games, murder mystery rooms, and hangouts for very large groups.", listSlugs: ["party", "more-than-4", "more-than-4", "cheap-co-op"], tags: ["social", "worlds", "party"], sessionLength: "one-night", steamAppId: 438100, minPlayers: 1, maxPlayers: 40, onlineCoop: true, localCoop: false, platforms: ["PC", "VR"], caveat: "Works without VR; choose private/group instances for friend nights." }),

  game({ slug: "rimworld", title: "RimWorld", description: "A colony story generator that becomes a shared chaos machine with multiplayer mods.", listSlugs: ["with-mods", "survival-groups", "campaign-co-op"], tags: ["colony sim", "strategy", "mods"], sessionLength: "campaign", steamAppId: 294100, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Multiplayer requires community mods, matching mod lists, and a patient host.", moddedPlayersLabel: "2-8 with mods", moddedMaxPlayers: 8, moddedSupportNote: "RimWorld Multiplayer says any player count is possible but recommends a maximum of 8. Best treated as a long-running modded campaign.", moddedSourceName: "RimWorld Multiplayer", moddedSourceUrl: "https://steamcommunity.com/sharedfiles/filedetails/?id=2606448745" }),
  game({ slug: "slay-the-spire", title: "Slay the Spire", description: "A solo deckbuilder that can become a lightweight shared run through co-op or race mods.", listSlugs: ["with-mods", "cheap-co-op"], tags: ["deckbuilder", "roguelike", "mods"], sessionLength: "one-night", steamAppId: 646570, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Multiplayer depends on community mods, so everyone needs the same setup.", moddedPlayersLabel: "Up to 10 friends with mods", moddedMaxPlayers: 11, moddedSupportNote: "Together in Spire advertises Steam or port-forwarded lobbies for up to 10 friends. Good for mod-tolerant roguelike nights.", moddedSourceName: "Together in Spire", moddedSourceUrl: "https://steamcommunity.com/sharedfiles/filedetails/?id=2384072973" }),
  game({ slug: "subnautica", title: "Subnautica", description: "Survival exploration that turns into a shared expedition through co-op mod setups.", listSlugs: ["with-mods", "survival-groups", "more-than-4"], tags: ["survival", "exploration", "mods"], sessionLength: "long-term", steamAppId: 264710, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Co-op requires mod setup and can have progression or sync rough edges.", moddedPlayersLabel: "Up to 100 with Nitrox", moddedMaxPlayers: 100, moddedSupportNote: "Nitrox advertises large-event support up to 100 slots, but normal friend groups should expect a smoother experience at much smaller counts.", moddedUnrestricted: true, moddedSourceName: "Nitrox", moddedSourceUrl: "https://nitrox.rux.gg/" }),
  game({ slug: "skyrim-special-edition", title: "The Elder Scrolls V: Skyrim Special Edition", description: "A solo RPG that can become a shared sandbox adventure with co-op mods.", listSlugs: ["with-mods", "campaign-co-op"], tags: ["rpg", "open world", "mods"], sessionLength: "campaign", steamAppId: 489830, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Co-op is modded, setup-heavy, and best with a small committed group.", moddedPlayersLabel: "Up to 8 with mods", moddedMaxPlayers: 8, moddedSupportNote: "Skyrim Together Reborn is widely documented as an 8-player co-op option, but quest and mod compatibility still need planning.", moddedSourceName: "Skyrim Together Reborn", moddedSourceUrl: "https://www.nexusmods.com/skyrimspecialedition/mods/69993" }),
  game({ slug: "elden-ring", title: "Elden Ring", description: "A harsh open-world action RPG that becomes a continuous co-op pilgrimage with Seamless Co-op.", listSlugs: ["with-mods", "campaign-co-op"], tags: ["soulslike", "open world", "mods"], sessionLength: "campaign", steamAppId: 1245620, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false, caveat: "Native co-op is session-based and restrictive. Seamless Co-op uses separate saves and its own connection flow.", moddedPlayersLabel: "Up to 5 with mods", moddedMaxPlayers: 5, moddedSupportNote: "Seamless Co-op is the established modded path for a start-to-finish shared run and removes many native summoning restrictions.", moddedSourceName: "Seamless Co-op", moddedSourceUrl: "https://www.nexusmods.com/eldenring/mods/510" }),
  game({ slug: "dark-souls-remastered", title: "Dark Souls Remastered", description: "A classic solo-first Souls journey that can become a more continuous co-op run through Seamless Co-op.", listSlugs: ["with-mods", "campaign-co-op"], tags: ["soulslike", "rpg", "mods"], sessionLength: "campaign", steamAppId: 570940, minPlayers: 1, maxPlayers: 4, onlineCoop: true, localCoop: false, caveat: "Native co-op is limited by summoning and boss boundaries. The mod is a better fit for planned friend playthroughs.", moddedPlayersLabel: "Up to 6 with mods", moddedMaxPlayers: 6, moddedSupportNote: "The Dark Souls Remastered Seamless Co-op mod is reported as synchronising progress and supporting up to six players total.", moddedSourceName: "Seamless Co-op", moddedSourceUrl: "https://www.nexusmods.com/darksoulsremastered/mods/899" }),
  game({ slug: "armored-core-6", title: "Armored Core VI: Fires of Rubicon", description: "A single-player mech campaign that becomes a squad mission night through the Armored Core Coop Mod.", listSlugs: ["with-mods", "campaign-co-op"], tags: ["mechs", "action", "mods"], sessionLength: "one-night", steamAppId: 1888160, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "The base campaign has no co-op. This is unofficial and best for PC groups comfortable with separate launchers.", moddedPlayersLabel: "Up to 6 with mods", moddedMaxPlayers: 6, moddedSupportNote: "Armored Core Coop Mod adds unofficial online co-op and community reports describe up to 6 players with enemy scaling.", moddedSourceName: "Armored Core Coop Mod", moddedSourceUrl: "https://www.nexusmods.com/armoredcore6firesofrubicon/mods/3" }),
  game({ slug: "sekiro", title: "Sekiro: Shadows Die Twice", description: "A solo sword-fighting game with an older online mod for PvP and small co-op experiments.", listSlugs: ["with-mods"], tags: ["soulslike", "action", "mods"], sessionLength: "one-night", steamAppId: 814380, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Sekiro Online is older and more experimental than the later Seamless Co-op projects.", moddedPlayersLabel: "2+ with mods", moddedMaxPlayers: 4, moddedSupportNote: "Sekiro Online adds PvP/co-op style online items, but treat it as a tinkering pick rather than a reliable group-night anchor.", moddedSourceName: "Sekiro Online", moddedSourceUrl: "https://www.nexusmods.com/sekiro/mods/577" }),
  game({ slug: "oxygen-not-included", title: "Oxygen Not Included", description: "A dense colony sim where a shared-base multiplayer mod lets multiple players coordinate one colony.", listSlugs: ["with-mods", "survival-groups"], tags: ["colony sim", "automation", "mods"], sessionLength: "campaign", steamAppId: 457140, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Current multiplayer projects are alpha/WIP and do not sync every system yet.", moddedPlayersLabel: "2+ with alpha mods", moddedMaxPlayers: 4, moddedSupportNote: "The Steam Workshop alpha says all players share controls over one colony and lists sync limitations, so keep expectations modest.", moddedSourceName: "ONI Multiplayer Mod", moddedSourceUrl: "https://steamcommunity.com/sharedfiles/filedetails/?id=2997749628" }),
  game({ slug: "hollow-knight", title: "Hollow Knight", description: "A single-player metroidvania that can become a shared exploration or randomizer night through HKMP.", listSlugs: ["with-mods", "cheap-co-op"], tags: ["metroidvania", "platformer", "mods"], sessionLength: "one-night", steamAppId: 367520, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Multiplayer is community-made and best with a group willing to use Hollow Knight mod tools.", moddedPlayersLabel: "2+ with HKMP", moddedMaxPlayers: 8, moddedSupportNote: "HKMP lets players host games and allow others to join their adventures; use ItemSync/randomizer notes for co-op-style runs.", moddedSourceName: "HKMP", moddedSourceUrl: "https://hkmp.org/" }),
  game({ slug: "kerbal-space-program", title: "Kerbal Space Program", description: "A single-player space-program sandbox that can become a shared universe through Luna Multiplayer or DarkMultiPlayer.", listSlugs: ["with-mods", "more-than-4"], tags: ["space", "simulation", "mods"], sessionLength: "campaign", steamAppId: 220200, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. Multiplayer depends on a server and agreement around time warp.", moddedPlayersLabel: "2+ with server mods", moddedMaxPlayers: 20, moddedSupportNote: "Luna Multiplayer and DarkMultiPlayer provide shared-universe server play, including time-sync/warp handling.", moddedSourceName: "Luna Multiplayer", moddedSourceUrl: "https://lunamultiplayer.com/" }),
  game({ slug: "beamng-drive", title: "BeamNG.drive", description: "A physics driving sandbox that becomes a casual group driving or racing server through BeamMP.", listSlugs: ["with-mods", "more-than-4", "party"], tags: ["driving", "sandbox", "mods"], sessionLength: "one-night", steamAppId: 284160, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Single-player by default. BeamMP requires its launcher and server browsing outside the base game.", moddedPlayersLabel: "Large servers with BeamMP", moddedMaxPlayers: 32, moddedSupportNote: "BeamMP is an active multiplayer mod with public servers and a large installed server ecosystem.", moddedUnrestricted: true, moddedSourceName: "BeamMP", moddedSourceUrl: "https://beammp.com/" }),
  game({ slug: "cities-skylines", title: "Cities: Skylines", description: "A city builder that can become a shared planning sandbox through the CSM multiplayer mod.", listSlugs: ["with-mods"], tags: ["city builder", "simulation", "mods"], sessionLength: "campaign", steamAppId: 255710, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. The multiplayer mod syncs many systems, but not every city simulation detail.", moddedPlayersLabel: "2+ with CSM", moddedMaxPlayers: 4, moddedSupportNote: "Cities: Skylines Multiplayer provides a client-server experience for users to build together in one city.", moddedSourceName: "Cities: Skylines Multiplayer", moddedSourceUrl: "https://citiesskylinesmultiplayer.com/" }),
  game({ slug: "just-cause-2", title: "Just Cause 2", description: "A single-player open-world chaos sandbox with a historic multiplayer mod built for huge servers.", listSlugs: ["with-mods", "more-than-4", "party"], tags: ["open world", "sandbox", "mods"], sessionLength: "one-night", steamAppId: 8190, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. The multiplayer mod is famous but much quieter now, so check server activity first.", moddedPlayersLabel: "Hundreds+ with mod", moddedMaxPlayers: 500, moddedSupportNote: "The Steam page describes extending Just Cause 2 to dozens, hundreds, or thousands of players; current population may be low.", moddedUnrestricted: true, moddedSourceName: "Just Cause 2 Multiplayer Mod", moddedSourceUrl: "https://store.steampowered.com/app/259080/Just_Cause_2_Multiplayer_Mod/" }),
  game({ slug: "just-cause-3", title: "Just Cause 3", description: "A solo open-world destruction sandbox with community multiplayer modes for freeroam, racing, and roleplay.", listSlugs: ["with-mods", "more-than-4", "party"], tags: ["open world", "sandbox", "mods"], sessionLength: "one-night", steamAppId: 225540, minPlayers: 1, maxPlayers: 1, onlineCoop: false, localCoop: false, caveat: "Solo by default. JC3 multiplayer exists, but server health varies and may be quiet.", moddedPlayersLabel: "Server-based with mod", moddedMaxPlayers: 32, moddedSupportNote: "JC3MP opens the game to community servers and custom game modes such as racing, deathmatch, roleplay, and freeroam.", moddedSourceName: "JC3MP", moddedSourceUrl: "https://just-cause.mp/" }),
  game({ slug: "cuphead", title: "Cuphead", description: "A two-player boss-rush classic with community mods that expand the local co-op count.", listSlugs: ["with-mods", "local-co-op", "cheap-co-op"], tags: ["boss rush", "local", "mods"], sessionLength: "one-night", steamAppId: 268910, minPlayers: 1, maxPlayers: 2, onlineCoop: false, localCoop: true, caveat: "Native co-op is two-player. Extra-player mods are local and niche.", localSetup: "controllers", localRequirement: "2 controllers (3 with mods)", moddedPlayersLabel: "3 with mods", moddedMaxPlayers: 3, moddedSupportNote: "Community mods expand Cuphead's local co-op limit to 3 simultaneous players.", moddedSourceName: "Cuphead 3 Players Multiplayer co-op", moddedSourceUrl: "https://www.nexusmods.com/cuphead/mods/140" }),
];

export function getCuratedList(slug: string) {
  return curatedLists.find((list) => list.slug === slug);
}

export function getCuratedGame(slug: string) {
  return curatedGames.find((game) => game.slug === slug);
}

export function curatedGamesForList(slug: string, minimumPlayers = 1) {
  return curatedGames.filter((game) => game.listSlugs.includes(slug) && supportsAtLeast(game, minimumPlayers));
}

export function supportsAtLeast(game: CuratedGame, minimumPlayers: number) {
  return Math.max(game.maxPlayers ?? 1, game.moddedMaxPlayers ?? 0) >= minimumPlayers;
}

export function curatedPlayerLabel(game: CuratedGame) {
  const nativeLabel =
    game.minPlayers === game.maxPlayers
      ? `${game.maxPlayers} player${game.maxPlayers === 1 ? "" : "s"}`
      : `Up to ${game.maxPlayers} players`;
  return game.moddedPlayersLabel ? `${nativeLabel}, ${game.moddedPlayersLabel}` : nativeLabel;
}

function game(seed: CuratedGameSeed): CuratedGame {
  return {
    slug: seed.slug,
    title: seed.title,
    description: seed.description,
    listSlugs: [...new Set(seed.listSlugs)],
    tags: seed.tags,
    sessionLength: seed.sessionLength,
    steamAppId: seed.steamAppId ?? null,
    minPlayers: seed.minPlayers,
    maxPlayers: seed.maxPlayers,
    onlineCoop: seed.onlineCoop,
    localCoop: seed.localCoop,
    gameModes: [seed.onlineCoop || seed.localCoop ? "Co-op" : "Multiplayer"],
    platforms: seed.platforms ?? ["PC"],
    genres: seed.tags,
    capabilitySource: "curated",
    capabilityConfidence: seed.caveat ? 0.75 : 0.9,
    trending: seed.trending,
    releaseStatus: seed.releaseStatus ?? "released",
    caveat: seed.caveat,
    localSetup: seed.localSetup,
    localRequirement: seed.localRequirement,
    moddedPlayersLabel: seed.moddedPlayersLabel,
    moddedMaxPlayers: seed.moddedMaxPlayers,
    moddedSupportNote: seed.moddedSupportNote,
    moddedUnrestricted: seed.moddedUnrestricted,
    moddedSourceName: seed.moddedSourceName,
    moddedSourceUrl: seed.moddedSourceUrl,
  };
}

